### ISSUE TITLE
支持Gravatar 头像 CDN

### ISSUE THREAD

**Issue by asforest** [innc11/AprilComment#2]
除了官方，也支持其它Gravatar 头像 CDN

**Comment by hajeekn** [comment]
建议独立出一个配置项配置Gravatar
甚至可以默认提供一个大陆镜像,然后如果用户配置了Gravatar项就采用用户配置的

**Comment by asforest** [comment]
> 建议独立出一个配置项配置Gravatar
> 甚至可以默认提供一个大陆镜像,然后如果用户配置了Gravatar项就采用用户配置的

嗯，在0.2.2版本里已经做进去了，可以配置头像源了，不过默认的Gravatar官方的，忘了改过来
